server.port: 8086

spring:
  application.name: ZipkinServer
  boot.admin.url: http://localhost:8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

management.security.enabled: false