server:
  port: 8082

spring.boot.admin.url: http://localhost:8080

spring:
  application:
    name: sampleService
  cloud:
    config:
     uri: http://localhost:8085
     profile:
      active: dev
     label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
